version: "3.9"

services:
  web:
    build: .
    container_name: django_app_habit
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: postgres_db_redis
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_habit
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery
    command: celery -A habit_tracker worker -l INFO
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: beat
    command: celery -A habit_tracker beat -l INFO
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: